# -*- coding: utf-8 -*-
"""class112.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CP6G6VAGjaxmCUiiUa8V-im7dUxvC_A
"""

print("Hello, World")

"""To upolad files in colab

"""

from google.colab import files
dataToLoad = files.upload()

from google.colab import files
csvData = files.upload()



from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""

import pandas as panda
import plotly.graph_objects as go
import csv

with open("savings.csv", newline='') as f:
  read = csv.reader(f)
  newData = list(read)
newData.pop(0)

reminded = 0
totalNumEntries = len(newData)
for data in newData:
  if int(data[3]) == 1:
    reminded += 1
print("Reminded: "+str(reminded))
print("Not Reminded: "+str(totalNumEntries-reminded))
print("Total Entries: "+str(totalNumEntries))

scgraph = go.Figure(go.Bar(x=["Reminded", "Not Reminded"],y=[reminded,totalNumEntries-reminded]))
scgraph.show()

